---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
```{r, echo=TRUE, results='hide'}
library(data.table)
library(plyr)
library(dplyr)
library(ggplot2)
```

## Loading and preprocessing the data
```{r, echo=TRUE}
activities <- read.csv("activity.csv", header=TRUE, colClasses=c("numeric", "Date", "numeric"))
activities <- data.table(activities)

act <- activities[!is.na(activities$step), ]
```
## What is mean total number of steps taken per day?

```{r, echo=TRUE}

dailyTotal <- act[, sum(steps), by=date]
dailyMean <- mean(dailyTotal$V1)
dailyMedian <- quantile(dailyTotal$V1, probs=0.5)
intervalMean <- act[, mean(steps), by=date]
meanofMean <- mean(intervalMean$V1)
plot(act$steps, type="l", ylab = "Nb of Steps",  xlab="Interval",
     main="NA removed")
abline(h=meanofMean, col="lightblue", lty=3)

intervalMedian <- act[, quantile(steps, probs=0.5), by=date]
paste("The Daily Means of steps is: ", round(dailyMean,2))
paste("The Daily Median of steps is: ",round(dailyMedian,2))
```
## What is the average daily activity pattern?
```{r, echo=TRUE}

maxdate <- intervalMean[which(intervalMean$V1 >= max(intervalMean$V1)),]$date
maxdateOnAct <- act[which(act$date == maxdate),]
highestStep <- max(maxdateOnAct$step)         
maxinterv <- maxdateOnAct[which(maxdateOnAct$step >= highestStep),]$interval
paste("The highest number of steps is: ", highestStep , "happened on: " ,
       maxdate , "on the interval: ", maxinterv)
```
## Imputing missing values
```{r, echo=TRUE}
activ <- activities
intervalMean2 <- activ[, mean(steps, na.rm=TRUE), by=date]

##This is applied for the case in which all the steps of all intervals are NA
intervalMean2[which(is.na(intervalMean2$V1)),]$V1 <- 0

xyz <- left_join(activ, intervalMean2, by="date")
for (i in 1:nrow(activ)) {
  if (is.na(activ[i]$steps)) activ[i]$steps <- xyz[i]$V1
}
```
```{r, echo=TRUE}
dailyTotal3 <- activ[, sum(steps), by=date]
intervalMean3 <- activ[, mean(steps), by=date]
intervalMedian3 <- activ[, quantile(steps, probs=0.5), by=date]

dailyMean3 <- mean(dailyTotal3$V1)
dailyMedian3 <- quantile(dailyTotal3$V1, probs=0.5)
paste("Mean of daily steps after simply removing NAs :", round(dailyMean,2))
paste("Mean after subtitution of NAs by mean of interval: ", round(dailyMean3,2))
paste("Median of daily steps after simply removing NAs : ", round(dailyMedian,2))
paste("Median after subtitution of NAs by mean of interval: ", round(dailyMedian3,2))

meanofMean3 <- mean(intervalMean3$V1)

par(mfrow=c(1,2))
plot(act$steps, type="l", ylab = "Nb of Steps",  xlab="Interval",
     main="NA removed")
abline(h=meanofMean, col="lightblue", lty=3)

plot(activ$steps, type="l", ylab = "Nb of Steps",  xlab="Interval",
     main="NA replaced by mean of interval")
abline(h=meanofMean3, col="red", lty=3)

par(mfrow=c(1,2))
plot(dailyTotal$V1, type="h", ylab="Total Steps per day", xlab = "Day",
     main="NA removed")

plot(dailyTotal3$V1, type="h" , ylab="Total daily Steps", xlab = "Day",
     main="NA replaced by mean of interval")

par(mfrow=c(1,2))
plot(intervalMean$V1, type="p", ylab="Mean Steps per Interval", xlab = "Day",
     main="NA removed")

plot(intervalMean3$V1, type="p", ylab="Mean Steps per Interval", xlab = "Day",
     main="NA replaced by mean of interval")
```

## Are there differences in activity patterns between weekdays and weekends?


```{r, echo=TRUE}
whichday <- function (dt) {
  wd <- weekdays(dt)
  if (wd %in% c("Monday", "Tuesday","Wednesday", "Thursday", "Friday"))
    return("weekday") 
  else
    return("weekend")
}
wday <- vector()
for (i in 1: nrow(activ)) {
  wday[i] <- whichday(activ[i]$date)
}
wday <- factor(wday)
activwd <- activ %>% mutate( wday=wday) %>%
             group_by(wday, interval) %>% summarise (meanInt = mean (steps))
ggplot(activwd, aes(interval, meanInt)) + geom_line() +
  facet_wrap( ~ wday, nrow=2) + 
  labs (title= "Average Interval Steps: Weekend vs Weekday") +
  theme(plot.title = element_text(size = rel(1.5), colour = "blue"))
zzz <- activwd[wday=="weekend",]
meanWE <- sum(zzz$meanInt)/nrow(zzz)
uuu <- activwd[wday=="weekday",]
meanWD <- sum(uuu$meanInt)/nrow(uuu)
paste("Walking more on the weekend")
paste("Mean step per interval during weekend: ", round(meanWE,2))
paste("Mean step per interval during weekday: ", round(meanWD,2))
```




